services:
  postgres:
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
  api:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      JWT_SECRET:
      JWT_EXPIRATION_SECONDS:
      DEFAULT_USER_USERNAME:
      DEFAULT_USER_PASSWORD:
    ports:
      - 8080:8080
    volumes:
      - api_logs:/logs

volumes:
  db_data:
  api_logs:
