spring.application.name=kiosk-zsp4
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.servlet.multipart.max-file-size=20GB
spring.servlet.multipart.max-request-size=20GB
app.asset.base-media-uri=/assets/media
