spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
app.auth.jwt.secret=${JWT_SECRET:pTRMQ8nt78z1Fb1I9wt/Co9sXoALN1cvvYSSiduqIQM=}
app.auth.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}
app.user.default-user.username=${DEFAULT_USER_USERNAME:admin}
app.user.default-user.password=${DEFAULT_USER_PASSWORD:admin}
logging.level.dev.rowinski.kioskzsp4=DEBUG
